export const FETCH_MATCHES_BEGIN = 'FETCH_MATCHES_BEGIN';
export const FETCH_MATCHES_SUCCESS = 'FETCH_MATCHES_SUCCESS';
export const FETCH_MATCHES_ERROR = 'FETCH_MATCHES_ERROR';

export const FETCH_LEAGUES_BEGIN = 'FETCH_LEAGUES_BEGIN';
export const FETCH_LEAGUES_SUCCESS = 'FETCH_LEAGUES_SUCCESS';
export const FETCH_LEAGUES_ERROR = 'FETCH_LEAGUES_ERROR';

export const LEAGUE_SELECTED = 'LEAGUE_SELECTED';